"use client";

import { useState } from "react";
import { Section } from "@/components/site/section";
import { Mono } from "@/components/ui/mono";

const FAQ_DATA = [
  {
    category: "General",
    items: [
      ["What is ZiggyDust?", "ZiggyDust is a platform that connects independent music artists with backers who loan funds for YouTube ad campaigns. Backers earn interest — a share of the incremental channel-wide YouTube AdSense revenue generated by the promotion. The platform facilitates the arrangement but does not hold funds or provide financial advice."],
      ["Is this like crowdfunding?", "Not exactly. Crowdfunding (like Kickstarter) is donation or reward-based — you give money and get a t-shirt. ZiggyDust is a performance-linked loan — backers loan funds that go exclusively to YouTube ads, and earn interest from the revenue uplift those ads create. Principal is repaid first, then interest accrues. There's real risk of loss."],
      ["Is this a security?", "ZiggyDust facilitates performance-linked loans between artists and backers. Backer funds are a loan — not an equity stake, not a royalty purchase. We are not a broker, exchange, or investment platform. However, the regulatory landscape is evolving. We recommend backers consult their own legal and financial advisors."],
    ],
  },
  {
    category: "For Artists",
    items: [
      ["What do I need to get started?", "An active YouTube channel with YouTube Partner Program (monetisation enabled), a LinkedIn profile, a Google Ads account, and your co-pay (minimum 20% of your total campaign budget)."],
      ["Do I give up any rights to my music?", "No. ZiggyDust never takes any ownership, licence, or control over your content. You retain full rights. The only obligation is the revenue share on incremental uplift for the duration of your drop's tenor."],
      ["What happens if the ads don't work?", "If there's no uplift above your baseline, there's nothing to share. Backers may lose their entire commitment. Your co-pay has already been deployed as ads. There's no refund mechanism post-deployment."],
      ["What's the 20% co-pay?", "You must contribute at least 20% of the total campaign budget from your own funds. This goes into the lockbox first and is deployed as ads first. It demonstrates genuine commitment and aligns your incentives with your backers."],
      ["Can I run multiple drops at once?", "No. One active drop per artist at a time. Complete or close your current drop before creating a new one. This keeps you focused and gives backers confidence that your attention isn't split."],
    ],
  },
  {
    category: "For Backers",
    items: [
      ["How do I earn money?", "Your funds are a performance-linked loan. The artist repays your principal first, then you earn interest — a percentage of the incremental channel-wide YouTube AdSense revenue above the pre-campaign baseline. This captures cross-views and discovery of older content. Paid monthly until your return cap is hit or the tenor expires."],
      ["Can I lose money?", "Yes. If the YouTube ads don't generate sufficient uplift, your loan may not be fully repaid — potentially not at all. The artist's 20% co-pay is first-loss, but there's no guarantee of return."],
      ["How do I know my money becomes ads?", "Every ad deployment is tracked with Google Ads invoice references, impression counts, view counts, and click-through rates. These receipts are visible on the drop page to all backers."],
      ["Who are the other backers?", "Every backer has a mandatory LinkedIn profile. The Backer Wall on each drop shows all backers' names, LinkedIn profiles, professional headlines, and track records. Full transparency."],
    ],
  },
  {
    category: "Platform",
    items: [
      ["Does ZiggyDust hold my money?", "No. ZiggyDust is a technology facilitator. Backer funds are a loan to the artist, not a deposit with us. Funds flow directly between participants and the escrow/lockbox. We have no custody at any point."],
      ["What happens if an artist defaults?", "Default triggers include: missed monthly payments, YouTube OAuth revocation, content deletion, and misrepresentation. Consequences include platform exclusion, public disclosure on their track record, and late payment penalties."],
      ["What's the baseline and how is it calculated?", "The baseline is the artist's average daily channel-wide YouTube AdSense revenue over the 30 days before the drop goes live. It's computed at launch and is non-disputable. Only channel-wide revenue above this baseline counts as uplift."],
    ],
  },
];

export default function FAQPage() {
  const [openKey, setOpenKey] = useState<string | null>(null);

  return (
    <div>
      <Section>
        <Mono className="text-[10px] text-ink-mid uppercase tracking-[0.15em] block mb-3">Questions</Mono>
        <h1 className="text-4xl lg:text-[52px] font-bold leading-[0.95] tracking-tight mb-4">FAQ</h1>
        <p className="text-base text-ink-mid leading-relaxed max-w-xl">Plain answers to the questions you should be asking.</p>
      </Section>

      <Section>
        {FAQ_DATA.map((cat, ci) => (
          <div key={ci} className="mb-8">
            <Mono className="text-[10px] text-amber uppercase tracking-widest block mb-4">
              {cat.category}
            </Mono>
            {cat.items.map(([q, a], qi) => {
              const key = `${ci}-${qi}`;
              const isOpen = openKey === key;
              return (
                <div
                  key={key}
                  className={`border-[1.5px] mb-2 bg-white transition-colors ${
                    isOpen ? "border-ink" : "border-sand"
                  }`}
                >
                  <button
                    onClick={() => setOpenKey(isOpen ? null : key)}
                    className="w-full px-4 lg:px-5 py-3.5 flex justify-between items-center cursor-pointer text-left bg-transparent border-0"
                  >
                    <span className="text-[15px] font-semibold text-ink pr-4">
                      {q}
                    </span>
                    <Mono className="text-lg text-amber shrink-0">
                      {isOpen ? "−" : "+"}
                    </Mono>
                  </button>
                  {isOpen && (
                    <div className="px-4 lg:px-5 pb-4 text-sm text-ink-mid leading-relaxed border-t border-sand pt-3.5">
                      {a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        ))}
      </Section>
    </div>
  );
}
